### ISSUE TITLE
Cleaner factory and directive syntax

### ISSUE THREAD

**Issue by ahmednuaman** [ahmednuaman/radian#18]
Following on from #16, @davej how would you deal with factories? And directives?

**Comment by davej** [comment]
I'm not sure it's needed to be honest, they don't really fit in with the class paradigm. I think it makes sense to have controllers and services because they fit the class paradigm quite naturally.

You could probably replicate the directive object literal as a class instead but I'm struggling to think of a good reason to do it and it would be very complicated. Maybe instead you could make a base class that only allows creation of very simple directives (just the link phase). Maybe it could accept an events object to allow easy binding, a lot of directives I write are simply for handling events that Angular doesn't handle natively. Perhaps something like:

```
class extends BaseSimpleDirective

  @register 'enterKey', [
    '$timeout'
    # @scope, @el and @attrs are automatically registered by the base class
    # This is probably a bit too magical for my liking.
  ]

  events:
    'keydown': 'onKeydown'
    # This is functionally equivalent to `@el.bind 'keydown', onKeydown` in the link phase

  onKeydown: (e) ->
    if e.keyCode is 13
      @$timeout ->
        @scope.$apply attrs.enterKey
      , + @attrs.enterKeyDelay

  init: ->
    # This would be the link phase of the directive.
    # It's not used in this example because event binding
    # is automatic using the events object
```

I'm really not convinced that we should do this though. I think it's best just to provide helpers for controllers and services for the moment. If we come up with compelling ways to implement the other types of constructs then great but there's not point much point in implementing them just because we can.

What do you think?

**Comment by ahmednuaman** [comment]
I had a think about this and really just wanted to tidy up the registering of these modules, so I created https://github.com/ahmednuaman/radian/blob/feature-18-an/assets/js/directive/radian-directive.coffee, https://github.com/ahmednuaman/radian/blob/feature-18-an/assets/js/factory/radian-factory.coffee and https://github.com/ahmednuaman/radian/tree/feature-18-an/assets/js/filter/radian-filter.coffee.

It just makes creating a directive, factory and filter as simple as a controller or service, without additional baggage or memory usage.
