### ISSUE TITLE
Use grunt-sass (and possibly bourbon)?

### ISSUE THREAD

**Issue by davej** [ahmednuaman/radian#28]
This is a feature request. I realise that Radian can't be everything to everybody but I think it's good to move away from the ruby dependencies where possible.

I've been using [grunt-sass](https://github.com/sindresorhus/grunt-sass) for a number of months now and I find it very stable, the only issue is that grunt-sass (and libsass) doesn't work with ruby libs like compass. I use [bourbon](http://bourbon.io/) instead and find it excellent. I also prefer scss to sass but that's very much a personal preference.

**Comment by ahmednuaman** [comment]
But bourbon is a gem? So how's that moving from Ruby dependencies?

**Comment by ahmednuaman** [comment]
Also, unless I'm mistaken, it doesn't have sprite support.

**Comment by davej** [comment]
Bourbon is available as a gem mainly for the command line tools, but you don't need to use it that way, it's just a set of mixins, ruby is not required.

Sprite generation would need to be done with something like https://github.com/selaux/node-sprite-generator. It possibly makes a bit of sense to separate the sprite generation task from compass anyway, especially if you plan to support other preprocessor in the future (node-sprite-generator supports sass/stylus/less/css).

**Comment by ahmednuaman** [comment]
Yep these can be options used in the generator, but I think this is making stuff too complex. The purpose of Radian is to keep things simple. Sass and compass are great because the `sass` syntax is inline with coffeescript and jade in that they're all based on whitespace rather than braces. And compass has all the great mixins that make building your site really quick.
